-- 1. 10.567을 소수점 둘째 자리까지 반올림
SELECT ROUND(10.567) FROM DUAL;     --11
-- 2. 10.567을 소수점 둘째 자리까지 버림
SELECT TRUNC(10.567) FROM DUAL;      --10
-- 3. 'ABCDEFG'에서 'CDE' 출력
SELECT SUBSTR('ABCDEFG', 3,3) FROM DUAL; -- CDE
-- 4. 'HELLO WORLD'에서 'WORLD' 시작 위치
SELECT REPLACE('HELLO WORLD', 'WORLD') FROM DUAL;
-- 5. 'AAA BBB CCC'에서 공백 제거
SELECT REPLACE('AAA BBB CCC', ' ','') FROM DUAL;
-- 6. 'ORACLE SQL'을 소문자로 변환
SELECT LOWER('ORACLE SQL')  FROM DUAL;
-- 7. 'oracle sql'을 첫 글자만 대문자로 변환
SELECT INITCAP('ORACLE SQL') FROM DUAL;
-- 8. 'DATABASE'에서 뒤에서 3글자 출력
SELECT SUBSTR('DATABASE', -3) FROM DUAL;
-- 9. 'A-B-C-D-E'에서 두 번째 '-' 위치 찾기
SELECT INSTR('A-B-C-D-E', '-' , 1, 2) FROM DUAL;------------------
-- 10. '010-1234-5678'에서 '-' 제거
SELECT REPLACE('010-1234-5678', '-', '') FROM DUAL;
-- 11. 현재 날짜를 'YYYY-MM-DD' 형식으로 출력
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')   FROM DUAL;
-- 12. NULL 값을 '없음'으로 변환
SELECT NVL(NULL, '없음')  FROM DUAL;
-- 13. SALARY가 10000 이상이면 '고급', 아니면 '일반' 출력
SELECT EMPLOYEE_ID, SALARY,
    CASE 
        WHEN SALARY >= 10000 THEN '고급'
        ELSE '일반'
    END
FROM EMPLOYEES
;
-- 14. EMPLOYEES에서 급여 내림차순 정렬
SELECT   * 
FROM     EMPLOYEES 
ORDER BY SALARY ASC
;
-- 15. 급여 상위 5명만 출력
SELECT *
FROM   
    (
    SELECT *
    FROM   EMPLOYEES
    ORDER BY SALARY DESC NULLS LAST
    ) 
    WHERE  ROWNUM <= 5
;
-- 16. 직원명(FIRST_NAME) + 부서명(DEPARTMENT_NAME) 출력
SELECT   E.FIRST_NAME
        ,D.DEPARTMENT_NAME
FROM    EMPLOYEES E
JOIN    DEPARTMENTS D
  ON    E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
-- 17. 부서 없는 직원도 포함해서 출력
SELECT   E.FIRST_NAME
        ,D.DEPARTMENT_NAME
FROM    EMPLOYEES E
LEFT JOIN    DEPARTMENTS D
  ON    E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
-- 18. 부서명이 'Sales'인 직원만 출력
SELECT   E.FIRST_NAME
        ,D.DEPARTMENT_NAME
FROM    EMPLOYEES E
LEFT JOIN    DEPARTMENTS D
  ON    E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(D.DEPARTMENT_NAME) = 'SALES'
;
-- 19. 급여가 5000~10000 사이인 직원
SELECT *
FROM    EMPLOYEES
WHERE  SALARY BETWEEN 5000 AND 10000
;
-- 20. EMPLOYEES에서 직원 수 출력
SELECT COUNT(*) FROM EMPLOYEES;

-- 21. 부서별 직원 수 출력
SELECT DEPARTMENT_ID, COUNT(*)
FROM    EMPLOYEES
GROUP BY DEPARTMENT_ID
;
-- 22. 부서별 평균 급여 출력
SELECT  DEPARTMENT_ID,
        AVG(SALARY)
FROM    EMPLOYEES
GROUP BY DEPARTMENT_ID
;
-- 23. 평균 급여 5000 이상인 부서만 출력
SELECT DEPARTMENT_ID,
        AVG(SALARY)
FROM    EMPLOYEES 
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>= 5000
;
-- 24. 전체 평균 급여보다 높은 직원 출력
/*
SELECT AVG(SALARY)     -- 6461.83....
FROM    EMPLOYEES
;
*/
SELECT  *
FROM    EMPLOYEES   
WHERE   SALARY > (
            SELECT AVG(SALARY)
            FROM    EMPLOYEES
            )
;
-- 25. 급여 상위 5명 출력 (서브쿼리 사용)
SELECT *
FROM 
    (
    SELECT  *
    FROM EMPLOYEES
    ORDER BY SALARY DESC NULLS LAST
    )
WHERE ROWNUM <=5
;
-- 26. 급여 순위 출력 (RANK 사용)
SELECT  EMPLOYEE_ID
        ,SALARY
        ,RANK() OVER(ORDER BY SALARY DESC NULLS LAST)
FROM EMPLOYEES
;
-- 27. 급여 순위 출력 (DENSE_RANK 사용)
SELECT  EMPLOYEE_ID
        ,SALARY
        ,DENSE_RANK() OVER(ORDER BY SALARY DESC NULLS LAST)
FROM EMPLOYEES
;
-- 28. 급여 기준 상위 10명 출력 (ROW_NUMBER 사용)
SELECT  *
FROM    (
        SELECT  EMPLOYEE_ID
                ,SALARY
                ,ROW_NUMBER() OVER (ORDER BY SALARY DESC NULLS LAST) RN
        FROM EMPLOYEES
        )
WHERE   RN <=10
;
-- 29. EMPLOYEES + JOB_HISTORY 사번, JOB_ID 합치기
    SELECT EMPLOYEE_ID, JOB_ID      --117까지 출력 ---------------------
    FROM    EMPLOYEES 
UNION
    SELECT EMPLOYEE_ID, JOB_ID
    FROM    JOB_HISTORY
;
-- 30. UNION과 UNION ALL 차이 직접 확인  
    SELECT EMPLOYEE_ID, JOB_ID      -- 119까지 출력
    FROM    EMPLOYEES 
UNION ALL
    SELECT EMPLOYEE_ID, JOB_ID
    FROM    JOB_HISTORY
;
-- 31. 직원 + 상사 이름 출력 (SELF JOIN)

-- 32. SALGRADE 테이블 이용해서 급여 등급 붙이기

-- 33. 급여를 4등분해서 등급 출력 (NTILE)

-- 34. 부서별 직원 이름을 한 줄로 출력 (LISTAGG)

-- 35. 입사 후 몇 개월 지났는지 출력

-- 36. 부서별 급여 합계, 평균, 인원수 출력

-- 37. 부서별 평균 급여가 4000 이상인 부서 출력

-- 38. 급여가 가장 높은 직원 1명 출력

-- 39. 급여가 두 번째로 높은 직원 출력 (동점 포함)

-- 40. 급여 낮은 순으로 5명 출력

-- 41. 직원명, 급여, 부서명 출력 (JOIN)

-- 42. 직원명, 급여, 등급(SALGRADE) 출력

-- 43. 직원명, 급여, 등급, 부서명 모두 출력

-- 44. 부서별 최고 급여 출력

-- 45. 부서별 최저 급여 출력

-- 46. 부서별 최고 급여 받는 직원 출력

-- 47. 전체에서 급여 상위 3명 출력

-- 48. 급여 순위 1~5등 출력 (동점 고려)

-- 49. 특정 부서(예: 50번) 직원만 정렬 출력

-- 50. EMPLOYEES 전체를 급여 기준으로 순위 + 등급 같이 출력

-- 1
SELECT ROUND(10.567, 2) FROM DUAL;

-- 2
SELECT TRUNC(10.567, 2) FROM DUAL;

-- 3
SELECT SUBSTR('ABCDEFG', 3, 3) FROM DUAL;

-- 4
SELECT INSTR('HELLO WORLD', 'WORLD') FROM DUAL;

-- 5
SELECT REPLACE('AAA BBB CCC', ' ', '') FROM DUAL;

-- 6
SELECT LOWER('ORACLE SQL') FROM DUAL;

-- 7
SELECT INITCAP('oracle sql') FROM DUAL;

-- 8
SELECT SUBSTR('DATABASE', -3) FROM DUAL;

-- 9
SELECT INSTR('A-B-C-D-E', '-', 1, 2) FROM DUAL;

-- 10
SELECT REPLACE('010-1234-5678', '-', '') FROM DUAL;

-- 11
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;

-- 12
SELECT NVL(NULL, '없음') FROM DUAL;

-- 13
SELECT FIRST_NAME, SALARY,
       CASE WHEN SALARY >= 10000 THEN '고급'
            ELSE '일반'
       END
FROM EMPLOYEES;

-- 14
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

-- 15
SELECT * FROM (
    SELECT * FROM EMPLOYEES ORDER BY SALARY DESC
) WHERE ROWNUM <= 5;

-- 16
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 17
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 18
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales';

-- 19
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

-- 20
SELECT COUNT(*) FROM EMPLOYEES;

-- 21
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 22
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 23
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) >= 5000;

-- 24
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- 25
SELECT * FROM (
    SELECT * FROM EMPLOYEES ORDER BY SALARY DESC
) WHERE ROWNUM <= 5;

-- 26
SELECT FIRST_NAME, SALARY,
       RANK() OVER (ORDER BY SALARY DESC)
FROM EMPLOYEES;

-- 27
SELECT FIRST_NAME, SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC)
FROM EMPLOYEES;

-- 28
SELECT * FROM (
    SELECT FIRST_NAME, SALARY,
           ROW_NUMBER() OVER (ORDER BY SALARY DESC) RN
    FROM EMPLOYEES
) WHERE RN <= 10;

-- 29
SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;

-- 30
SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;

-- 31
SELECT E2.FIRST_NAME 직원, E1.FIRST_NAME 상사
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID;

-- 32
SELECT E.FIRST_NAME, E.SALARY, SG.GRADE
FROM EMPLOYEES E
LEFT JOIN SALGRADE SG
ON E.SALARY BETWEEN SG.LOSAL AND SG.HISAL;

-- 33
SELECT FIRST_NAME, SALARY,
       NTILE(4) OVER (ORDER BY SALARY DESC)
FROM EMPLOYEES;

-- 34
SELECT DEPARTMENT_ID,
       LISTAGG(FIRST_NAME, ',') WITHIN GROUP (ORDER BY FIRST_NAME)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 35
SELECT FIRST_NAME,
       MONTHS_BETWEEN(SYSDATE, HIRE_DATE)
FROM EMPLOYEES;

-- 36
SELECT DEPARTMENT_ID,
       COUNT(*), SUM(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 37
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) >= 4000;

-- 38
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- 39
SELECT *
FROM (
    SELECT FIRST_NAME, SALARY,
           DENSE_RANK() OVER (ORDER BY SALARY DESC) R
    FROM EMPLOYEES
)
WHERE R = 2;

-- 40
SELECT *
FROM EMPLOYEES
ORDER BY SALARY ASC
FETCH FIRST 5 ROWS ONLY;

-- 41
SELECT E.FIRST_NAME, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 42
SELECT E.FIRST_NAME, E.SALARY, SG.GRADE
FROM EMPLOYEES E
LEFT JOIN SALGRADE SG
ON E.SALARY BETWEEN SG.LOSAL AND SG.HISAL;

-- 43
SELECT E.FIRST_NAME, E.SALARY, SG.GRADE, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN SALGRADE SG
ON E.SALARY BETWEEN SG.LOSAL AND SG.HISAL
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 44
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 45
SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 46
SELECT *
FROM EMPLOYEES E
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
);

-- 47
SELECT *
FROM (
    SELECT * FROM EMPLOYEES ORDER BY SALARY DESC
)
WHERE ROWNUM <= 3;

-- 48
SELECT *
FROM (
    SELECT FIRST_NAME, SALARY,
           DENSE_RANK() OVER (ORDER BY SALARY DESC) R
    FROM EMPLOYEES
)
WHERE R BETWEEN 1 AND 5;

-- 49
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
ORDER BY SALARY DESC;

-- 50
SELECT FIRST_NAME, SALARY,
       RANK() OVER (ORDER BY SALARY DESC) 순위,
       NTILE(5) OVER (ORDER BY SALARY DESC) 등급
FROM EMPLOYEES;