CREATE TABLE TUSER (
     USERID      VARCHAR2(20)  NOT NULL PRIMARY KEY  
    , USERNAME   VARCHAR2(20)  NOT NULL       
    , EMAIL      VARCHAR2(320) UNIQUE         
 );
 
 
 INSERT INTO TUSER( USERID,USERNAME,EMAIL) VALUES ( 'ABA','가가','ABA@naver.com');
INSERT INTO TUSER( USERID,USERNAME,EMAIL) VALUES ( 'ABB','가나','ABB@naver.com');
INSERT INTO TUSER( USERID,USERNAME,EMAIL) VALUES ( 'ABC','가다','ABC@naver.com');
INSERT INTO TUSER( USERID,USERNAME,EMAIL) VALUES ( 'ABD','가라','ABD@naver.com');
INSERT INTO TUSER( USERID,USERNAME,EMAIL) VALUES ( 'ABE','가마','ABE@naver.com');


ALTER TABLE TUSER ADD (
    PASSWORD    VARCHAR2(20)    DEFAULT 1234  NOT NULL
   , REGDATE    DATE DEFAULT    SYSDATE 
   , USERNUM    NUMBER(6)       
);

CREATE SEQUENCE SEQ_TUSER;

SELECT * FROM TUSER;


INSERT INTO TUSER(USERID, USERNAME, EMAIL, PASSWORD, USERNUM)  VALUES ( 'ABF','가바','ABF@naver.com','123456',SEQ_ID.NEXTVAL);














